# Generated by Django 4.0 on 2021-12-29 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 1, 13, 46, 911014, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
